default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

# CubeGuyMaze:
#     buffer_size: 250000
#     buffer_init_steps: 10000
#     init_entcoef: 0.85
#     time_horizon: 2048
#     max_steps: 5.0e5
#     hidden_units: 256
#     # vis_encode_type: nature_cnn
#     reward_signals:
#         curiosity:
#             strength: 0.1
#             gamma: 0.99
#             encoding_size: 256

CubeGuyMazeRaycast:
    buffer_size: 100000
    buffer_init_steps: 2500
    init_entcoef: 0.85
    time_horizon: 256
    max_steps: 1.0e6
    hidden_units: 256
    reward_signals:
        curiosity:
            strength: 0.07
            gamma: 0.99
            encoding_size: 256